//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: inertia_protocol
// ----------------------------------------------------------------------------
pub mod inertia_protocol {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for inertia_protocol
    pub fn program_id() -> Pubkey {
        pubkey!("8ST3LRU5gv8ijZehvXdwRzc6VnvqbVozCCdFzEzqhqbW")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: CleanupExpiredEscrow
    // ....................................................................

    /// Main instruction struct for CleanupExpiredEscrow
    pub struct CleanupExpiredEscrowInstruction {
        pub accounts: CleanupExpiredEscrowInstructionAccountMetas,
        pub data: CleanupExpiredEscrowInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CleanupExpiredEscrow instruction
    #[derive(Debug, Clone, Default)]
    pub struct CleanupExpiredEscrowInstructionAccountMetas {
        pub caller: AccountMeta,

        pub escrow: AccountMeta,

        pub user_wallet: AccountMeta,
    }

    /// Account pubkeys for CleanupExpiredEscrow instruction
    #[derive(Debug, Clone)]
    pub struct CleanupExpiredEscrowInstructionAccounts {
        pub caller: Pubkey,

        pub escrow: Pubkey,

        pub user_wallet: Pubkey,
    }

    impl CleanupExpiredEscrowInstructionAccounts {
        pub fn new(caller: Pubkey, escrow: Pubkey, user_wallet: Pubkey) -> Self {
            Self {
                caller,

                escrow,

                user_wallet,
            }
        }
    }

    /// Instruction data for CleanupExpiredEscrow
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CleanupExpiredEscrowInstructionData {}

    impl CleanupExpiredEscrowInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CleanupExpiredEscrowInstruction
    impl CleanupExpiredEscrowInstruction {
        fn discriminator() -> [u8; 8] {
            [197u8, 214u8, 51u8, 163u8, 114u8, 209u8, 68u8, 130u8]
        }

        pub fn data(data: CleanupExpiredEscrowInstructionData) -> Self {
            Self {
                accounts: CleanupExpiredEscrowInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CleanupExpiredEscrowInstructionAccounts) -> Self {
            self.accounts.caller = AccountMeta::new(accounts.caller, true);

            self.accounts.escrow = AccountMeta::new(accounts.escrow, false);

            self.accounts.user_wallet = AccountMeta::new(accounts.user_wallet, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.caller.clone());

            metas.push(self.accounts.escrow.clone());

            metas.push(self.accounts.user_wallet.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ExecuteSwap
    // ....................................................................

    /// Main instruction struct for ExecuteSwap
    pub struct ExecuteSwapInstruction {
        pub accounts: ExecuteSwapInstructionAccountMetas,
        pub data: ExecuteSwapInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ExecuteSwap instruction
    #[derive(Debug, Clone, Default)]
    pub struct ExecuteSwapInstructionAccountMetas {
        pub caller: AccountMeta,

        pub escrow: AccountMeta,

        pub user_wallet: AccountMeta,

        pub partner_wallet: AccountMeta,

        pub treasury: AccountMeta,

        pub user_input_token_account: AccountMeta,

        pub destination_token_account: AccountMeta,

        pub swap_program: AccountMeta,

        pub token_program: AccountMeta,

        pub instructions_sysvar: AccountMeta,
    }

    /// Account pubkeys for ExecuteSwap instruction
    #[derive(Debug, Clone)]
    pub struct ExecuteSwapInstructionAccounts {
        pub caller: Pubkey,

        pub escrow: Pubkey,

        pub user_wallet: Pubkey,

        pub partner_wallet: Pubkey,

        pub user_input_token_account: Pubkey,

        pub destination_token_account: Pubkey,

        pub swap_program: Pubkey,
    }

    impl ExecuteSwapInstructionAccounts {
        pub fn new(
            caller: Pubkey,

            escrow: Pubkey,

            user_wallet: Pubkey,

            partner_wallet: Pubkey,

            user_input_token_account: Pubkey,

            destination_token_account: Pubkey,

            swap_program: Pubkey,
        ) -> Self {
            Self {
                caller,

                escrow,

                user_wallet,

                partner_wallet,

                user_input_token_account,

                destination_token_account,

                swap_program,
            }
        }
    }

    /// Instruction data for ExecuteSwap
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ExecuteSwapInstructionData {
        pub swap_instruction_data: Vec<u8>,
    }

    impl ExecuteSwapInstructionData {
        pub fn new(swap_instruction_data: Vec<u8>) -> Self {
            Self {
                swap_instruction_data,
            }
        }
    }

    /// Implementation for ExecuteSwapInstruction
    impl ExecuteSwapInstruction {
        fn discriminator() -> [u8; 8] {
            [56u8, 182u8, 124u8, 215u8, 155u8, 140u8, 157u8, 102u8]
        }

        pub fn data(data: ExecuteSwapInstructionData) -> Self {
            Self {
                accounts: ExecuteSwapInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ExecuteSwapInstructionAccounts) -> Self {
            self.accounts.caller = AccountMeta::new(accounts.caller, true);

            self.accounts.escrow = AccountMeta::new(accounts.escrow, false);

            self.accounts.user_wallet = AccountMeta::new(accounts.user_wallet, false);

            self.accounts.partner_wallet = AccountMeta::new(accounts.partner_wallet, false);

            self.accounts.treasury = AccountMeta::new(
                pubkey!("AX32tpNHzJsDvYvSuuT7NCiSQy6tMMyDdvrNzGYm8tYK"),
                false,
            );

            self.accounts.user_input_token_account =
                AccountMeta::new(accounts.user_input_token_account, false);

            self.accounts.destination_token_account =
                AccountMeta::new(accounts.destination_token_account, false);

            self.accounts.swap_program = AccountMeta::new_readonly(accounts.swap_program, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.instructions_sysvar = AccountMeta::new_readonly(
                pubkey!("Sysvar1nstructions1111111111111111111111111"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.caller.clone());

            metas.push(self.accounts.escrow.clone());

            metas.push(self.accounts.user_wallet.clone());

            metas.push(self.accounts.partner_wallet.clone());

            metas.push(self.accounts.treasury.clone());

            metas.push(self.accounts.user_input_token_account.clone());

            metas.push(self.accounts.destination_token_account.clone());

            metas.push(self.accounts.swap_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.instructions_sysvar.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeEscrow
    // ....................................................................

    /// Main instruction struct for InitializeEscrow
    pub struct InitializeEscrowInstruction {
        pub accounts: InitializeEscrowInstructionAccountMetas,
        pub data: InitializeEscrowInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeEscrow instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeEscrowInstructionAccountMetas {
        pub user_wallet: AccountMeta,

        pub user_input_token_account: AccountMeta,

        pub expected_destination_token_account: AccountMeta,

        pub escrow: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeEscrow instruction
    #[derive(Debug, Clone)]
    pub struct InitializeEscrowInstructionAccounts {
        pub user_wallet: Pubkey,

        pub user_input_token_account: Pubkey,

        pub expected_destination_token_account: Pubkey,

        pub escrow: Pubkey,
    }

    impl InitializeEscrowInstructionAccounts {
        pub fn new(
            user_wallet: Pubkey,

            user_input_token_account: Pubkey,

            expected_destination_token_account: Pubkey,

            escrow: Pubkey,
        ) -> Self {
            Self {
                user_wallet,

                user_input_token_account,

                expected_destination_token_account,

                escrow,
            }
        }
    }

    /// Instruction data for InitializeEscrow
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeEscrowInstructionData {
        pub params: InitializeEscrowParams,
    }

    impl InitializeEscrowInstructionData {
        pub fn new(params: InitializeEscrowParams) -> Self {
            Self { params }
        }
    }

    /// Implementation for InitializeEscrowInstruction
    impl InitializeEscrowInstruction {
        fn discriminator() -> [u8; 8] {
            [243u8, 160u8, 77u8, 153u8, 11u8, 92u8, 48u8, 209u8]
        }

        pub fn data(data: InitializeEscrowInstructionData) -> Self {
            Self {
                accounts: InitializeEscrowInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeEscrowInstructionAccounts) -> Self {
            self.accounts.user_wallet = AccountMeta::new(accounts.user_wallet, true);

            self.accounts.user_input_token_account =
                AccountMeta::new(accounts.user_input_token_account, false);

            self.accounts.expected_destination_token_account =
                AccountMeta::new_readonly(accounts.expected_destination_token_account, false);

            self.accounts.escrow = AccountMeta::new(accounts.escrow, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user_wallet.clone());

            metas.push(self.accounts.user_input_token_account.clone());

            metas.push(self.accounts.expected_destination_token_account.clone());

            metas.push(self.accounts.escrow.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SelfRescue
    // ....................................................................

    /// Main instruction struct for SelfRescue
    pub struct SelfRescueInstruction {
        pub accounts: SelfRescueInstructionAccountMetas,
        pub data: SelfRescueInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SelfRescue instruction
    #[derive(Debug, Clone, Default)]
    pub struct SelfRescueInstructionAccountMetas {
        pub user_wallet: AccountMeta,

        pub escrow: AccountMeta,

        pub user_input_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for SelfRescue instruction
    #[derive(Debug, Clone)]
    pub struct SelfRescueInstructionAccounts {
        pub user_wallet: Pubkey,

        pub escrow: Pubkey,

        pub user_input_token_account: Pubkey,
    }

    impl SelfRescueInstructionAccounts {
        pub fn new(user_wallet: Pubkey, escrow: Pubkey, user_input_token_account: Pubkey) -> Self {
            Self {
                user_wallet,

                escrow,

                user_input_token_account,
            }
        }
    }

    /// Instruction data for SelfRescue
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SelfRescueInstructionData {}

    impl SelfRescueInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for SelfRescueInstruction
    impl SelfRescueInstruction {
        fn discriminator() -> [u8; 8] {
            [122u8, 22u8, 229u8, 109u8, 41u8, 88u8, 207u8, 19u8]
        }

        pub fn data(data: SelfRescueInstructionData) -> Self {
            Self {
                accounts: SelfRescueInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SelfRescueInstructionAccounts) -> Self {
            self.accounts.user_wallet = AccountMeta::new(accounts.user_wallet, true);

            self.accounts.escrow = AccountMeta::new(accounts.escrow, false);

            self.accounts.user_input_token_account =
                AccountMeta::new(accounts.user_input_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user_wallet.clone());

            metas.push(self.accounts.escrow.clone());

            metas.push(self.accounts.user_input_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: TopUpBuffer
    // ....................................................................

    /// Main instruction struct for TopUpBuffer
    pub struct TopUpBufferInstruction {
        pub accounts: TopUpBufferInstructionAccountMetas,
        pub data: TopUpBufferInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for TopUpBuffer instruction
    #[derive(Debug, Clone, Default)]
    pub struct TopUpBufferInstructionAccountMetas {
        pub contributor: AccountMeta,

        pub escrow: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for TopUpBuffer instruction
    #[derive(Debug, Clone)]
    pub struct TopUpBufferInstructionAccounts {
        pub contributor: Pubkey,

        pub escrow: Pubkey,
    }

    impl TopUpBufferInstructionAccounts {
        pub fn new(contributor: Pubkey, escrow: Pubkey) -> Self {
            Self {
                contributor,

                escrow,
            }
        }
    }

    /// Instruction data for TopUpBuffer
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct TopUpBufferInstructionData {
        pub amount: u64,
    }

    impl TopUpBufferInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for TopUpBufferInstruction
    impl TopUpBufferInstruction {
        fn discriminator() -> [u8; 8] {
            [112u8, 8u8, 168u8, 233u8, 111u8, 232u8, 177u8, 16u8]
        }

        pub fn data(data: TopUpBufferInstructionData) -> Self {
            Self {
                accounts: TopUpBufferInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: TopUpBufferInstructionAccounts) -> Self {
            self.accounts.contributor = AccountMeta::new(accounts.contributor, true);

            self.accounts.escrow = AccountMeta::new(accounts.escrow, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.contributor.clone());

            metas.push(self.accounts.escrow.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ----------------------------------------------------------------------------
// Program: mock_dex
// ----------------------------------------------------------------------------
pub mod mock_dex {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for mock_dex
    pub fn program_id() -> Pubkey {
        pubkey!("4uGiKQe9yiD9bCKX9nRrVZot9HkPKV7w8GN8acoAkYyP")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: Swap
    // ....................................................................

    /// Main instruction struct for Swap
    pub struct SwapInstruction {
        pub accounts: SwapInstructionAccountMetas,
        pub data: SwapInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Swap instruction
    #[derive(Debug, Clone, Default)]
    pub struct SwapInstructionAccountMetas {
        pub source: AccountMeta,

        pub destination: AccountMeta,

        pub authority: AccountMeta,

        pub token_program: AccountMeta,

        pub source_mint: AccountMeta,

        pub output_mint: AccountMeta,

        pub mint_authority: AccountMeta,
    }

    /// Account pubkeys for Swap instruction
    #[derive(Debug, Clone)]
    pub struct SwapInstructionAccounts {
        pub source: Pubkey,

        pub destination: Pubkey,

        pub authority: Pubkey,

        pub source_mint: Pubkey,

        pub output_mint: Pubkey,

        pub mint_authority: Pubkey,
    }

    impl SwapInstructionAccounts {
        pub fn new(
            source: Pubkey,

            destination: Pubkey,

            authority: Pubkey,

            source_mint: Pubkey,

            output_mint: Pubkey,

            mint_authority: Pubkey,
        ) -> Self {
            Self {
                source,

                destination,

                authority,

                source_mint,

                output_mint,

                mint_authority,
            }
        }
    }

    /// Instruction data for Swap
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SwapInstructionData {
        pub amount_in: u64,

        pub amount_out: u64,
    }

    impl SwapInstructionData {
        pub fn new(amount_in: u64, amount_out: u64) -> Self {
            Self {
                amount_in,

                amount_out,
            }
        }
    }

    /// Implementation for SwapInstruction
    impl SwapInstruction {
        fn discriminator() -> [u8; 8] {
            [248u8, 198u8, 158u8, 145u8, 225u8, 117u8, 135u8, 200u8]
        }

        pub fn data(data: SwapInstructionData) -> Self {
            Self {
                accounts: SwapInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SwapInstructionAccounts) -> Self {
            self.accounts.source = AccountMeta::new(accounts.source, false);

            self.accounts.destination = AccountMeta::new(accounts.destination, false);

            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.source_mint = AccountMeta::new(accounts.source_mint, false);

            self.accounts.output_mint = AccountMeta::new(accounts.output_mint, false);

            self.accounts.mint_authority =
                AccountMeta::new_readonly(accounts.mint_authority, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.source.clone());

            metas.push(self.accounts.destination.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.source_mint.clone());

            metas.push(self.accounts.output_mint.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: EscrowState
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct EscrowState {
    pub user_wallet: Pubkey,

    pub partner_wallet: Pubkey,

    pub user_input_token_account: Pubkey,

    pub input_amount: u64,

    pub expected_program_id: Pubkey,

    pub expected_discriminator: [u8; 8],

    pub expected_destination_token_account: Pubkey,

    pub expected_output_amount: u64,

    pub gas_buffer_lamports: u64,

    pub creation_slot: u64,

    pub ttl_slots: u64,

    pub nonce: u64,

    pub status: EscrowStatus,

    pub bump: u8,
}

impl EscrowState {
    pub fn new(
        user_wallet: Pubkey,

        partner_wallet: Pubkey,

        user_input_token_account: Pubkey,

        input_amount: u64,

        expected_program_id: Pubkey,

        expected_discriminator: [u8; 8],

        expected_destination_token_account: Pubkey,

        expected_output_amount: u64,

        gas_buffer_lamports: u64,

        creation_slot: u64,

        ttl_slots: u64,

        nonce: u64,

        status: EscrowStatus,

        bump: u8,
    ) -> Self {
        Self {
            user_wallet,

            partner_wallet,

            user_input_token_account,

            input_amount,

            expected_program_id,

            expected_discriminator,

            expected_destination_token_account,

            expected_output_amount,

            gas_buffer_lamports,

            creation_slot,

            ttl_slots,

            nonce,

            status,

            bump,
        }
    }
}

/// Custom enum: EscrowStatus
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum EscrowStatus {
    Pending,

    Executed,

    Rescued,

    Expired,
}

/// Custom struct: InitializeEscrowParams
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct InitializeEscrowParams {
    pub nonce: u64,

    pub gas_buffer_lamports: u64,

    pub dynamic_minimum_lamports: u64,

    pub partner_wallet: Pubkey,

    pub input_amount: u64,

    pub expected_program_id: Pubkey,

    pub expected_discriminator: [u8; 8],

    pub expected_output_amount: u64,
}

impl InitializeEscrowParams {
    pub fn new(
        nonce: u64,

        gas_buffer_lamports: u64,

        dynamic_minimum_lamports: u64,

        partner_wallet: Pubkey,

        input_amount: u64,

        expected_program_id: Pubkey,

        expected_discriminator: [u8; 8],

        expected_output_amount: u64,
    ) -> Self {
        Self {
            nonce,

            gas_buffer_lamports,

            dynamic_minimum_lamports,

            partner_wallet,

            input_amount,

            expected_program_id,

            expected_discriminator,

            expected_output_amount,
        }
    }
}

/// Custom struct: SwapExecuted
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct SwapExecuted {
    pub escrow: Pubkey,

    pub user_wallet: Pubkey,

    pub was_rescue: bool,

    pub caller: Pubkey,

    pub output_amount: u64,
}

impl SwapExecuted {
    pub fn new(
        escrow: Pubkey,

        user_wallet: Pubkey,

        was_rescue: bool,

        caller: Pubkey,

        output_amount: u64,
    ) -> Self {
        Self {
            escrow,

            user_wallet,

            was_rescue,

            caller,

            output_amount,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
